[project]
name = "nlp-md-proc-toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "streamlit>=1.45.0",
]

[build-system]
requires = ['setuptools']
build-backend = "setuptools.build_meta"